spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
jwt:
  secret: sakjhgdfksljbvdkbjkebwflkasjknvxckljw